export const ADD_DATABASES_SUCC = "ADD_DATABASES_SUCC";
export const ADD_DATABASES_ERR = "ADD_DATABASES_ERR";
export const DROP_DATABASES_SUCC = "DROP_DATABASES_SUCC";
export const DROP_DATABASES_ERR = "DROP_DATABASES_ERR";
export const ADD_TABLE_SUCC = "ADD_TABLE_SUCC";
export const ADD_TABLE_ERR = "ADD_TABLE_ERR";
export const DROP_TABLE_SUCC = "DROP_TABLE_SUCC";
export const DROP_TABLE_ERR = "DROP_TABLE_ERR";
